// Here we have constants to be utilised during productPage validations
const productPageConstants = [
  {
    cat: "phone",
    desc: "The Samsung Galaxy S6 is powered by 1.5GHz octa-core Samsung Exynos 7420 processor and it comes with 3GB of RAM. The phone packs 32GB of internal storage cannot be expanded.",
    id: 1,
    img: "imgs/galaxy_s6.jpg",
    price: 360,
    title: "Samsung galaxy s6",
  },
  {
    cat: "phone",
    desc: "The Nokia Lumia 1520 is powered by 2.2GHz quad-core Qualcomm Snapdragon 800 processor and it comes with 2GB of RAM. ",
    id: 2,
    img: "imgs/Lumia_1520.jpg",
    price: 820,
    title: "Nokia lumia 1520",
  },
  {
    cat: "phone",
    desc: "The Motorola Google Nexus 6 is powered by 2.7GHz quad-core Qualcomm Snapdragon 805 processor and it comes with 3GB of RAM.",
    id: 3,
    img: "imgs/Nexus_6.jpg",
    price: 650,
    title: "Nexus 6",
  },
  {
    cat: "phone",
    desc: "The Samsung Galaxy S7 is powered by 1.6GHz octa-core it comes with 4GB of RAM. The phone packs 32GB of internal storage that can be expanded up to 200GB via a microSD card.",
    id: 4,
    img: "imgs/galaxy_s6.jpg",
    price: 800,
    title: "Samsung galaxy s7",
  },
  {
    cat: "phone",
    desc: "It comes with 1GB of RAM. The phone packs 16GB of internal storage cannot be expanded. As far as the cameras are concerned, the Apple iPhone 6 packs a 8-megapixel primary camera on the rear and a 1.2-megapixel front shooter for selfies.",
    id: 5,
    img: "imgs/iphone_6.jpg",
    price: 790,
    title: "Iphone 6 32gb",
  },
  {
    cat: "phone",
    desc: "Sony Xperia Z5 Dual smartphone was launched in September 2015. The phone comes with a 5.20-inch touchscreen display with a resolution of 1080 pixels by 1920 pixels at a PPI of 424 pixels per inch.",
    id: 6,
    img: "imgs/xperia_z5.jpg",
    price: 320,
    title: "Sony xperia z5",
  },
  {
    cat: "phone",
    desc: "The HTC One M9 is powered by 1.5GHz octa-core Qualcomm Snapdragon 810 processor and it comes with 3GB of RAM. The phone packs 32GB of internal storage that can be expanded up to 128GB via a microSD card.",
    id: 7,
    img: "imgs/HTC_M9.jpg",
    price: 700,
    title: "HTC One M9",
  },
  {
    cat: "notebook",
    desc: "Sony is so confident that the VAIO S is a superior ultraportable laptop that the company proudly compares the notebook to Apple's 13-inch MacBook Pro. And in a lot of ways this notebook is better, thanks to a lighter weight.",
    id: 8,
    img: "imgs/sony_vaio_5.jpg",
    price: 790,
    title: "Sony vaio i5",
  },
  {
    cat: "notebook",
    desc: "REVIEW Sony is so confident that the VAIO S is a superior ultraportable laptop that the company proudly compares the notebook to Apple's 13-inch MacBook Pro. And in a lot of ways this notebook is better, thanks to a lighter weight, higher-resolution display, more storage space, and a Blu-ray drive..",
    id: 9,
    img: "imgs/sony_vaio_5.jpg",
    price: 790,
    title: "Sony vaio i7",
  },
  {
    cat: "notebook",
    desc: "1.6GHz dual-core Intel Core i5 (Turbo Boost up to 2.7GHz) with 3MB shared L3 cacheConfigurable to 2.2GHz dual-core Intel Core i7 (Turbo Boost up to 3.2GHz) with 4MB shared L3 cache.",
    id: 11,
    img: "imgs/macbook_air.jpg",
    price: 700,
    title: "MacBook air",
  },
  {
    cat: "notebook",
    desc: "6th Generation Intel Core i7-6500U Dual-Core Processor 2.5 GHz (max boost speed up to 3.1GHz) 4MB L3 Cache, 8GB DDR4 1600 MHz, 1TB 5400 RPM HDD15.6 in Full HD LED-backlit touchscreen with Truelife (1920 x 1080), 10-finger multi-touch support, Intel HD Graphics 520 with shared graphics memory",
    id: 12,
    img: "imgs/dell.jpg",
    price: 700,
    title: "Dell i7 8gb",
  },
  {
    cat: "notebook",
    desc: "7th Gen Intel Core i7-7500U mobile processor 2.70 GHz with Turbo Boost Technology up to 3.50 GHz, Intel HD Graphics 62015.6 inch Full HD IPS TrueLife LED-backlit touchscreen (1920 x 1080), 10-finger multi-touch support, 360° flip-and-fold design,8GB DDR4 2400 MHz Memory, 1TB 5400 RPM HDD, No optical drive, 3 in 1 card reader (SD SDHC SDXC)",
    id: 13,
    img: "imgs/dell.jpg",
    price: 700,
    title: "2017 Dell 15.6 Inch",
  },
  {
    cat: "notebook",
    desc: "Apple has introduced three new versions of its MacBook Pro line, including a 13-inch and 15-inch model with the Touch Bar, a thin, multi-touch strip display that sits above the MacBook Pro's keyboard..",
    id: 15,
    img: "imgs/macbook_air.jpg",
    price: 1100,
    title: "MacBook Pro",
  },
  {
    cat: "monitor",
    desc: 'LED Cinema Display features a 27-inch glossy LED-backlit TFT active-matrix LCD display with IPS technology and an optimum resolution of 2560x1440. It has a 178 degree horizontal and vertical viewing angle, a "typical" brightness of 375 cd/m2, contrast ratio of 1000:1, and a 12 ms response time.',
    id: 10,
    img: "imgs/apple_cinema.jpg",
    price: 400,
    title: "Apple monitor 24",
  },
  {
    cat: "monitor",
    desc: "ASUS VS247H-P 23.6- Inch Full HD",
    id: 14,
    img: "imgs/asusm.jpg",
    price: 230,
    title: "ASUS Full HD",
  },
];

module.exports = productPageConstants;
